# SPDX-FileCopyrightText: 2026 Sayam Sriphua
# SPDX-License-Identifier: MIT
"""A pull request's description credits nobody who did not sign (ADR 0013).

Gates `pr-description-credits-the-signer` and `pr-description-checker-proven-two-way`. What is
refused is a line that opens with the credit, not a sentence that mentions one; and the
description, which a stranger writes, reaches the checker through the environment and never
through a script.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOL = ROOT / "tools" / "lint_pr_body.py"
WORKFLOW = ROOT / ".github" / "workflows" / "pr-description.yml"
sys.path.insert(0, str(ROOT / "tools"))
import lint_commits  # noqa: E402
import lint_pr_body  # noqa: E402

# the footer an assistant appends by default: a credit, a blank line, a link to its session
FOOTER = "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_0000000000000000\n"


def test_an_assistant_s_default_footer_is_refused_line_by_line():
    problems = lint_pr_body.check_body("## What changes\n\nA thing.\n\n" + FOOTER)
    assert [n for n, _ in problems] == [5, 7]
    assert "credits Claude Code" in problems[0][1] and "link to an assistant's session" in problems[1][1]
    # GitHub sends a description typed in its own editor with CRLF line ends
    assert [n for n, _ in lint_pr_body.check_body(FOOTER.replace("\n", "\r\n"))] == [1, 3]


@pytest.mark.parametrize("line", [
    "Co-authored-by: Claude <noreply@anthropic.com>",
    "co-authored-by: Someone Else <s@example.org>",  # the key is what is refused, as in a commit
    "Claude-Session: https://claude.ai/code/session_x",
    "Generated with Claude Code",
    "✨ *Generated by GitHub Copilot*",
    "- Generated with [Cursor](https://cursor.com)",
    "> 🤖 generated with [claude code](https://claude.com/claude-code)",
    "https://claude.ai/code/session_0000000000000000",
    "<https://claude.ai/share/abc>",
    "https://chatgpt.com/share/abc-def",
])
def test_a_line_that_opens_with_an_assistant_s_credit_is_refused(line):
    assert [n for n, _ in lint_pr_body.check_body("body\n" + line + "\nmore")] == [2], line


@pytest.mark.parametrize("body", [
    None, "", "Fixes the caption.\n",
    # saying what the rule refuses is not breaking it: mid-sentence, or quoted in backticks
    "A `Co-authored-by:` trailer is refused, as is `Claude-Session:`.",
    "`Co-authored-by:` trailers are refused.",
    "`🤖 Generated with [Claude Code]` was the footer; it is gone.",
    "The footer read Generated with Claude Code and a session link, https://claude.ai/code/session_x, after it.",
    # a source, a tool of our own, and a person
    "| One short entry per platform | [anthropics/skills](https://github.com/anthropics/skills) |",
    "Generated with tools/gen_settings_docs.py, as the settings reference always is.",
    "Generated by the build, byte for byte.",
    "Claude Shannon's entropy, for the curious: https://example.org/claude.ai/code/",
    "Signed-off-by: Sayam Sriphua <976721+sayam@users.noreply.github.com>",
])
def test_a_description_that_credits_no_assistant_passes(body):
    assert lint_pr_body.check_body(body) == []


def test_the_trailer_keys_are_the_commit_linter_s_own():
    """One list: a key the commit linter learns to refuse is refused in a description too."""
    assert lint_pr_body.FORBIDDEN_TRAILERS is lint_commits.FORBIDDEN_TRAILERS
    for key in lint_commits.FORBIDDEN_TRAILERS:
        assert lint_pr_body.check_body(key + ": x"), key


def _run(args: list[str], body: str | None) -> subprocess.CompletedProcess:
    env = {k: v for k, v in os.environ.items() if k != "PR_BODY"}
    if body is not None:
        env["PR_BODY"] = body
    return subprocess.run([sys.executable, str(TOOL), *args], capture_output=True, text=True, env=env, timeout=60)


def test_the_command_reads_the_environment_or_a_file_and_says_which_line(tmp_path):
    clean = _run([], "Fixes the caption.")
    assert clean.returncode == 0 and "credits nobody who did not sign" in clean.stdout
    assert _run([], "").returncode == 0, "an empty description credits nobody"
    red = _run([], "One.\n\n" + FOOTER)
    assert red.returncode == 1 and red.stderr == ""
    assert "description line 3 credits Claude Code" in red.stdout and "description line 5 is a link" in red.stdout
    assert "runs again when it is edited" in red.stdout
    # a description is data: nothing in it is run, expanded or read as an option
    hostile = _run([], "$(touch " + str(tmp_path / "owned") + ")\n`id`\n--file /etc/passwd\n")
    assert hostile.returncode == 0 and not (tmp_path / "owned").exists()
    path = tmp_path / "description.md"
    path.write_text(FOOTER, encoding="utf-8")
    assert _run(["--file", str(path)], None).returncode == 1
    nothing = _run([], None)
    assert nothing.returncode == 2 and "set PR_BODY or pass --file" in nothing.stderr, "silence is not a pass"


def test_the_workflow_hands_the_description_over_as_data_and_runs_again_on_an_edit():
    text = WORKFLOW.read_text(encoding="utf-8")
    code = "\n".join(line for line in text.split("\n") if not line.lstrip().startswith("#"))
    # through the environment, once — and never inside `run:`, where ${{ }} is pasted into a
    # shell script before the shell sees it, so a description could end the command and start another
    assert code.count("${{") == 1 and "          PR_BODY: ${{ github.event.pull_request.body }}" in code
    runs = re.findall(r"^\s*run: (.*)$", code, re.MULTILINE)
    assert runs == ["python3 tools/lint_pr_body.py"]
    # fixing a refused description is an edit, so an edit must run the check again
    assert "    types: [opened, edited, reopened, synchronize]" in code
    # a fork's pull request runs with a read-only token and no secrets; pull_request_target would not
    assert "pull_request_target" not in code and re.search(r"^on:\n  pull_request:\n", code, re.MULTILINE)
    assert "\npermissions:\n  contents: read\n" in code and code.count("permissions:") == 1
    assert "continue-on-error" not in code
