# SPDX-FileCopyrightText: 2026 Sayam Sriphua
# SPDX-License-Identifier: MIT
"""Bundle js/*.js and the shared assets into skills/thai-docx/scripts/thai_docx.js.

    python3 tools/bundle_js.py           # write the bundle
    python3 tools/bundle_js.py --check   # exit 1 if the committed bundle is stale

One file, no modules, no dependencies: it runs under Node.js as a command and in
a sandbox that evaluates JavaScript, where it defines `ThaiDocx` (ADR 0008).

Role: generator (writes the bundle) and decider (`--check`).
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / "skills" / "thai-docx"
OUT = SKILL / "scripts" / "thai_docx.js"
# a part's SPDX lines at its top: the bundle states them once, in its own header
SPDX = re.compile(r"\A(?://[ ]SPDX-[\w-]+:[ ][^\n]*\n)+")
# what the bundle hands a caller, as `module.exports` and as `ThaiDocx`
API = ("VERSION", "buildDocument", "checkDocument", "buildText", "checkBytes", "parseMarkdown", "plainText", "parseArgs", "pyDumps",
       "DEFAULTS", "SETTINGS", "QUESTIONS", "cliMain")


def bundle() -> str:
    version = re.search(r'__version__ = "([^"]+)"', (SKILL / "scripts" / "thai_docx" / "__init__.py").read_text()).group(1)
    ooxml = json.loads((SKILL / "assets" / "ooxml.json").read_text(encoding="utf-8"))
    entities = json.loads((SKILL / "assets" / "entities.json").read_text(encoding="utf-8"))
    sources, licenses, holders = [], [], []
    for path in sorted((ROOT / "js").glob("*.js")):
        text = path.read_text(encoding="utf-8")
        head = SPDX.match(text)
        for line in head.group(0).splitlines() if head else []:
            key, value = line[len("// SPDX-"):].split(": ", 1)
            if key == "License-Identifier":  # the parts join licences with AND only
                licenses += [v for v in value.split(" AND ") if v not in licenses]
            elif value not in holders:
                holders.append(value)
        sources.append("// ---- " + path.name + " " + "-" * max(0, 70 - len(path.name)) + "\n" + text[head.end() if head else 0:])
    body = "\n".join(sources)
    body = body.replace("/*@@OOXML@@*/ null", json.dumps(ooxml, ensure_ascii=True, sort_keys=True, separators=(",", ":")))
    xml_names = json.loads((SKILL / "assets" / "xml-names.json").read_text(encoding="utf-8"))
    body = body.replace("/*@@XML_NAMES@@*/ null", json.dumps(xml_names, separators=(",", ":")))
    body = body.replace("/*@@ENTITIES@@*/ null", json.dumps(entities, ensure_ascii=True, sort_keys=True, separators=(",", ":")))
    assert "@@" not in body, "an asset placeholder was not replaced"
    return (
        "#!/usr/bin/env node\n"
        + "".join("// SPDX-FileCopyrightText: " + holder + "\n" for holder in holders)
        + "// SPDX-License-Identifier: " + " AND ".join(licenses) + "\n"
        "// thai-docx " + version + " — Thai-correct .docx from Markdown, and a checker for any .docx.\n"
        "// Generated by tools/bundle_js.py from js/*.js and assets/; do not edit by hand.\n"
        "// MIT (LICENSE.txt). The Markdown parser ports commonmark.js 0.31.2, BSD-2-Clause (LICENSES/commonmark.js.txt).\n"
        "//\n"
        "//   node scripts/thai_docx.js build IN.md OUT.docx [flags]\n"
        "//   node scripts/thai_docx.js check FILE.docx\n"
        "//\n"
        "// In a JavaScript sandbox with no files: ThaiDocx.buildDocument(markdown, flags, images) → { result, bytes }.\n"
        "(function (root) {\n"
        '"use strict";\n'
        "const VERSION = " + json.dumps(version) + ";\n"
        + body
        + "\nconst api = { " + ", ".join(API) + " };\n"
        'if (typeof module !== "undefined" && module.exports) module.exports = api;\n'
        "root.ThaiDocx = api;\n"
        'if (typeof require !== "undefined" && typeof module !== "undefined" && require.main === module) '
        "process.exitCode = cliMain(process.argv.slice(2));\n"
        '})(typeof globalThis !== "undefined" ? globalThis : this);\n'
    )


def main(argv: list[str]) -> int:
    text = bundle()
    if argv == ["--check"]:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("skills/thai-docx/scripts/thai_docx.js is stale: run python3 tools/bundle_js.py")
            return 1
        print("bundle is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("wrote " + str(OUT.relative_to(ROOT)) + " (" + str(len(text.encode("utf-8"))) + " bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
