# SPDX-FileCopyrightText: 2026 Sayam Sriphua
# SPDX-License-Identifier: MIT
"""A pull request's description credits nobody who did not sign (ADR 0013).

    PR_BODY="$(gh pr view 12 --json body --jq .body)" python3 tools/lint_pr_body.py
    python3 tools/lint_pr_body.py --file description.md

`tools/lint_commits.py` refuses `Co-authored-by:` and `Claude-Session:` in a commit: the person
who signed is the author, and a tool that helped write a change is not (ADR 0013). A pull
request's description is published under the same name, so it is held to the same rule.

A line is refused when it **opens** with one of:

- a trailer key the commit linter refuses (`Co-authored-by:`, `Claude-Session:`);
- "Generated with" or "Generated by" and the name of a coding assistant, after any emoji;
- a link to an assistant's session, alone on its line.

A description may still say what the rule refuses: a mention in the middle of a sentence, or
quoted in backticks, opens no line.

The description arrives in the environment, never on the command line and never pasted into a
script: it is text a stranger writes.

Role: decider — it answers pass or fail and returns an exit code that can block a pull request.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from lint_commits import FORBIDDEN_TRAILERS  # noqa: E402  one list of keys, held in one place

__all__ = ["ASSISTANTS", "check_body", "main"]

# coding assistants that sign what they helped write, by default
ASSISTANTS = ("Claude Code", "Claude", "GitHub Copilot", "Copilot", "Codex", "ChatGPT", "Cursor", "Gemini", "Aider")
SESSION_HOSTS = (r"claude\.ai/(?:code|share|chat)/", r"chatgpt\.com/(?:share|c)/")

# what may stand before the words on the line: emoji, list marks, emphasis — but not a backtick,
# which makes the line a quotation of the footer rather than the footer
_LEAD = r"^[^\w`]*"
TRAILER = re.compile(_LEAD + r"(" + "|".join(re.escape(key) for key in FORBIDDEN_TRAILERS) + r")\s*:", re.IGNORECASE)
GENERATED = re.compile(_LEAD + r"generated (?:with|by) \[?(" + "|".join(re.escape(name) for name in ASSISTANTS) + r")\b", re.IGNORECASE)
SESSION = re.compile(r"^\s*<?https?://(?:www\.)?(?:" + "|".join(SESSION_HOSTS) + r")\S*>?\s*$", re.IGNORECASE)


def check_body(body: str | None) -> list[tuple[int, str]]:
    """Every refused line, as (line number, why). An empty description passes: it credits nobody."""
    problems = []
    for number, line in enumerate((body or "").replace("\r\n", "\n").split("\n"), start=1):
        trailer, generated = TRAILER.match(line), GENERATED.match(line)
        if trailer:
            problems.append((number, f"opens with a `{trailer.group(1)}:` trailer — credit goes to the person who signed, alone"))
        elif generated:
            problems.append((number, f"credits {generated.group(1)} — a tool that helped write a change is not its author"))
        elif SESSION.match(line):
            problems.append((number, "is a link to an assistant's session — the description stands on its own"))
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--file", type=pathlib.Path, help="read the description from a file instead of $PR_BODY")
    args = parser.parse_args(argv)
    if args.file is not None:
        body = args.file.read_text(encoding="utf-8")
    elif "PR_BODY" in os.environ:
        body = os.environ["PR_BODY"]
    else:
        print("lint_pr_body: no description given — set PR_BODY or pass --file", file=sys.stderr)
        return 2
    problems = check_body(body)
    for number, why in problems:
        print(f"description line {number} {why}")
    if problems:
        print("\nRemove the line and save the description; the check runs again when it is edited (ADR 0013).")
        return 1
    print("the description credits nobody who did not sign")
    return 0


if __name__ == "__main__":
    sys.exit(main())
